version: "2"
services:
  # api:
  #   build: .
  #   restart: always
  #   ports:
  #   - "4000:4000"
  #   links:
  #     - mongo
  #   environment:
  #     DBSTRING: mongodb://mongo:27017/DB
  #   depends_on:
  #   - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"